global:
  scrape_interval: 15s
rule_files:
  - "prometheus_rules.yml"
  - "alert_rules.yml"
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'docker'
    static_configs:
    - targets: ['172.31.26.8:8080', '172.31.26.108:8080']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.26.8:9100', '172.31.26.108:9100']